
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.mycompany.project1.parser.operaciones;

/** CUP generated class containing symbol constants. */
public class Parser2Sym {
  /* terminals */
  public static final int INT = 5;
  public static final int MENOS = 3;
  public static final int MULT = 4;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int ADD = 2;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int FLOAT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADD",
  "MENOS",
  "MULT",
  "INT",
  "FLOAT",
  "STRING",
  "ID"
  };
}

