
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package com.mycompany.project1.parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int MENOR = 18;
  public static final int CADENA = 3;
  public static final int INT = 31;
  public static final int IGUAL = 13;
  public static final int DECIMAL = 4;
  public static final int LEER = 14;
  public static final int DEFECTO = 30;
  public static final int PAREN_O = 7;
  public static final int SWITCH = 25;
  public static final int ID = 34;
  public static final int PARA = 20;
  public static final int MENORIG = 23;
  public static final int STRING = 33;
  public static final int CASO = 27;
  public static final int COMA = 21;
  public static final int FLOAT = 32;
  public static final int MAYOR = 17;
  public static final int EOF = 0;
  public static final int MULT = 12;
  public static final int PAREN_C = 8;
  public static final int DIFERENTE = 24;
  public static final int SINO = 6;
  public static final int IGUALC = 19;
  public static final int ADD = 10;
  public static final int MAYORIG = 22;
  public static final int SI = 5;
  public static final int ESCRIBIR = 15;
  public static final int error = 1;
  public static final int LLAVE_C = 29;
  public static final int LLAVE_A = 28;
  public static final int ENTERO = 2;
  public static final int PCOMA = 9;
  public static final int MIENTRAS = 16;
  public static final int DPUNTOS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "CADENA",
  "DECIMAL",
  "SI",
  "SINO",
  "PAREN_O",
  "PAREN_C",
  "PCOMA",
  "ADD",
  "MENOS",
  "MULT",
  "IGUAL",
  "LEER",
  "ESCRIBIR",
  "MIENTRAS",
  "MAYOR",
  "MENOR",
  "IGUALC",
  "PARA",
  "COMA",
  "MAYORIG",
  "MENORIG",
  "DIFERENTE",
  "SWITCH",
  "DPUNTOS",
  "CASO",
  "LLAVE_A",
  "LLAVE_C",
  "DEFECTO",
  "INT",
  "FLOAT",
  "STRING",
  "ID"
  };
}

